### ISSUE TITLE
Leftnav dropdown arrow overflows when text is exactly the width of the leftnav box

### ISSUE THREAD

**Issue by oliverli** [isomerpages/isomerpages-template#146]
See https://mlaw-io-staging.netlify.com/bankruptcy/bankruptcy-notice/

![screenshot of leftnav dropdown arrow intersecting with the line](https://user-images.githubusercontent.com/1127543/61845580-82ab2780-aed6-11e9-8b7c-61d0271d9513.png)

**Comment by lisatjide** [comment]
verified and checked that issue is no longer there.
