### ISSUE TITLE
Tooling for redirection server

### ISSUE THREAD

**Issue by prestonlimlianjie** [isomerpages/isomerpages-template#151]
Currently, the redirection server is an NGINX server running on a single EC2 instance. To set up a new website, we need to SSH into the server and update the `nginx.conf` and save the SSL cert into the Amazon Elastic File storage.

**Problem**
The current `nginx.conf` file is not version controlled, so developers can't track when the file has changed. We could version the NGINX files on GitHub and deploy it via Travis CI to Amazon Elastic Beanstalk.

However, there is a catch: we can't store the SSL certificate and key on GitHub.

**Exploration**
Figure out how to automate SSL certificate deployment onto our redirection server

**Comment by lisa-kwok** [comment]
closing this issue as it has been addressed by:
1. making nginx config on [isomer-redirection](https://github.com/isomerpages/isomer-redirection) repo.
2. adding certs directly into s3
