### ISSUE TITLE
Explore using GitHub Templates to create new Isomer sites

### ISSUE THREAD

**Issue by prestonlimlianjie** [isomerpages/isomerpages-template#154]
Currently, the Isomer PM needs to use the [generate-site Python CLI](https://github.com/isomerpages/generate-site) to create a new site on their local machine before pushing it to GitHub. 

Explore if GitHub Templates can reduce the need to maintain a Python CLI tool/allow the PM to create new sites directly on GitHub.

**Comment by serverwentdown** [comment]
GitHub Templates is effectively `cp -R`.

**Comment by lisa-kwok** [comment]
issue no longer valid since we have a site generation form which helps with this process
