### ISSUE TITLE
User self service FAQ 

### ISSUE THREAD

**Issue by lisatjide** [isomerpages/isomerpages-template#157]
**Problem:** Currently the onboarding of users and troubleshooting are handled manually by PM and engineer. This is very time consuming and most of these questions are often very basic questions on formatting and how to use github. 

**Proposed solution:**
Can we explore coming up with a smart FAQ? chatbot? etc to help users answers these queries better?

e.g https://support.google.com/chrome/?hl=en#topic=7438008

**Comment by lisa-kwok** [comment]
closing this since we now incorporate onboarding flow into CMS
