### ISSUE TITLE
Centralize Lighthouse tests

### ISSUE THREAD

**Issue by prestonlimlianjie** [isomerpages/isomerpages-template#161]
We currently integrate Lighthouse tests to each Isomer repo via Travis CI. This is great because it means that Lighthouse audits are run each time a merge to `master` happens.

However, this has added a lot of configuration steps - the Isomer engineers need to add Travis CI to each repo. Instead, we could centralize all of our test suites for all Isomer sites into one single repo containing a list of all Isomer sites, and set a Travis-CRON job to run once a day.

We could also extend this to SSL Labs testing to ensure that our SSL configurations are appropriately done.

**Comment by lisatjide** [comment]
issue closed since we no longer implement lighthouse check
