### ISSUE TITLE
Automated site generation

### ISSUE THREAD

**Issue by lisatjide** [isomerpages/isomerpages-template#192]
**Is your feature request related to a problem? Please describe.**
Site generation is currently manually done by cloning the template's next-gen branch. 
When a request for a new site is received through email. User will be instructed to create a Github account, provide their username and isomer team will add them into the respective repository. 

However, this method proves to be time consuming and it involved multiple back and forth between users and isomer team. 

**Describe the solution you'd like**
Ideal state of site generation should not take more than 5-10mins if Github account creation has been done. 
User will submit a form with the necessary usernames of the admins. Upon submission, an empty site template will be spinned up. Note that the verification of user identity and request should be done before a site template is provisioned. 
This is not a major issue since this does not affect any production sites.

**Comment by lisa-kwok** [comment]
closing this issue as site generation form has addressed this. thanks @LoneRifle!
