### ISSUE TITLE
Missing right padding on left nav pages 

### ISSUE THREAD

**Issue by lisatjide** [isomerpages/isomerpages-template#195]
**Describe the bug**
There is no right padding which causes the share icons to flush all the way to the right.
See examples https://www.sgclean.gov.sg/join/for-individuals/, https://www.customs.gov.sg/individuals/going-through-customs/arrivals

<img width="1392" alt="Screenshot 2020-09-30 at 5 34 11 PM" src="https://user-images.githubusercontent.com/23736580/94669596-09ae2800-0344-11eb-8a51-96a18e3126c4.png">
<img width="1392" alt="Screenshot 2020-09-30 at 5 40 37 PM" src="https://user-images.githubusercontent.com/23736580/94669615-10d53600-0344-11eb-8131-d4f851499ba6.png">

**To Reproduce**
Access any left nav pages on isomer sites and view it on 100%. 

**Expected behavior**
There should be adequate padding on the right at 100% zoom level. Below example is when zoom level is at 90%
<img width="1392" alt="Screenshot 2020-09-30 at 5 47 09 PM" src="https://user-images.githubusercontent.com/23736580/94670326-fd769a80-0344-11eb-9ef8-641aded65216.png">

**Comment by lisa-kwok** [comment]
seems like issue is no longer there
