### ISSUE TITLE
shareicon is not rendered correctly on all v2 sites

### ISSUE THREAD

**Issue by lisa-kwok** [isomerpages/isomerpages-template#212]
**Describe the bug**
The facebook, linkedin and email icons are rendered in different colors and has odd paddings. 

**To Reproduce**
Go to any pages (other than homepage) on v2 sites

<img width="510" alt="Screenshot 2020-12-09 at 1 09 21 AM" src="https://user-images.githubusercontent.com/23736580/101517188-67519700-39bb-11eb-9493-a675a721b389.png">

**Ideal Behaviour**
<img width="459" alt="Screenshot 2020-12-09 at 1 11 14 AM" src="https://user-images.githubusercontent.com/23736580/101517262-85b79280-39bb-11eb-8c7a-ba8ae0fec99f.png">

**Comment by LoneRifle** [comment]
This is due to #205, a reapplication of #183, which removed the button tag from the sharing icons. Let me reinstate that now.

**Comment by LoneRifle** [comment]
Fixed in f7ae6b0
