### ISSUE TITLE
integrate VICA into Isomer

### ISSUE THREAD

**Issue by lisa-kwok** [isomerpages/isomerpages-template#230]
To incorporate VICA into Isomer including necessary whitelisting of their domain

https://webchat.vica.gov.sg/static/css/chat.css
https://webchat.vica.gov.sg/static/js/chat.js
vica.gov.sg

**Comment by prestonlimlianjie** [comment]
This has been done - there are new issues with the VICA integration but we will create a new issue to discuss it.
