### ISSUE TITLE
breadcrumb showing on google search instead of title

### ISSUE THREAD

**Issue by jacksonOGP** [isomerpages/isomerpages-template#237]
Some of the search on google return the breadcrumb instead of title. (see ss) 

This happens to other isomer sites as well. Is there anything we can do in our backend? 

![Title](https://user-images.githubusercontent.com/70509050/126119962-57dce41c-875b-4cf6-9dcd-fd8661173e0a.png)]

![Staging site](https://user-images.githubusercontent.com/70509050/126122108-b31afcf6-b87d-4e36-a813-532b718611bc.png)

**Comment by prestonlimlianjie** [comment]
Seems like this has been resolved?
![Screenshot 2022-02-07 at 5 20 59 PM](https://user-images.githubusercontent.com/19917616/152760288-1dedb686-5fd5-4560-9f73-d111f0b6b662.png)
