### ISSUE TITLE
New masthead should show up in staging and prod-v1 sites

### ISSUE THREAD

**Issue by prestonlimlianjie** [isomerpages/isomerpages-template#241]
The current new masthead is only applied to prod sites that use the `isomerpages-template@next-gen` remote theme. We should apply it to staging and prod-v1 sites that use the `isomerpages-template` remote theme.

**Comment by alexanderleegs** [comment]
Staging was actually already covered - the issue for v1 sites has been addressed in https://github.com/isomerpages/isomerpages-template/pull/242
