### ISSUE TITLE
Use Of Customise Font

### ISSUE THREAD

**Issue by mrizhar3110** [isomerpages/isomerpages-template#397]
Hi,

I would like to inquire regarding the use of customise fonts or what are the list of fonts available? 

 I have attached a mock up design of the font that I would like use and was hoping that I could get some assistance on how to go about it.
 
 
![Screenshot 2024-03-26 at 9 32 52 AM](https://github.com/isomerpages/isomerpages-template/assets/109506880/33ffe25c-be60-42f6-9c12-c1479b27fb81)
![Screenshot 2024-03-26 at 9 33 11 AM](https://github.com/isomerpages/isomerpages-template/assets/109506880/ff25762b-1f80-4cbc-9d8d-ef2033126272)
![Screenshot 2024-03-26 at 9 35 14 AM](https://github.com/isomerpages/isomerpages-template/assets/109506880/6300f2aa-bdc4-4da0-8386-2ea869fee522)
![Screenshot 2024-03-26 at 9 35 25 AM](https://github.com/isomerpages/isomerpages-template/assets/109506880/48ca8f82-fd7b-429d-885b-e6ee8b409661)

**Comment by dcshzj** [comment]
Hi @mrizhar3110, we are unfortunately not taking support tickets or feature requests directly on this issue tracker. Please contact us at support@isomer.gov.sg so we can address your queries. Thank you!
